Repository matt-usurp/pilgrim, pull requests merged in 2021-01, with the labels that each got.

#5 feat: add event type maps for all sources defined in aws-lambda
  src/provider/aws/execution/aws-lambda-alb.ts
  src/provider/aws/execution/aws-lambda-apigw-authorizer.ts
  src/provider/aws/execution/aws-lambda-appsync.ts
  src/provider/aws/execution/aws-lambda-cloudformation.ts
  src/provider/aws/execution/aws-lambda-cloudfront.ts
  src/provider/aws/execution/aws-lambda-cloudwatch.ts
  src/provider/aws/execution/aws-lambda-codebuild.ts
  src/provider/aws/execution/aws-lambda-codepipeline.ts
  src/provider/aws/execution/aws-lambda-cognito.ts
  src/provider/aws/execution/aws-lambda-connect.ts
  src/provider/aws/execution/aws-lambda-dynamodb.ts
  src/provider/aws/execution/aws-lambda-eventbridge.ts
  src/provider/aws/execution/aws-lambda-iot.ts
  src/provider/aws/execution/aws-lambda-kinesis.ts
  src/provider/aws/execution/aws-lambda-lex.ts
  src/provider/aws/execution/aws-lambda-msk.ts
  src/provider/aws/execution/aws-lambda-s3.ts
  src/provider/aws/execution/aws-lambda-ses.ts
  src/provider/aws/execution/aws-lambda-sns.ts
  src/provider/aws/execution/aws-lambda-sqs.ts
Labels: enhancement

#6 docs(readme): fix code examples
  README.md
Labels: documentation

#7 ci: implement caching example
  .github/workflows/build.yaml
  .github/workflows/commit.yaml
Labels: enhancement

#8 fix: aws lambda types not working because of module syntax
  src/provider/aws.ts
  src/provider/aws/execution/aws-lambda-alb.ts
  src/provider/aws/execution/aws-lambda-apigw-authorizer.ts
  src/provider/aws/execution/aws-lambda-apigw-v1.ts
  src/provider/aws/execution/aws-lambda-apigw-v2.ts
  src/provider/aws/execution/aws-lambda-appsync.ts
  src/provider/aws/execution/aws-lambda-cloudformation.ts
  src/provider/aws/execution/aws-lambda-cloudfront.ts
  src/provider/aws/execution/aws-lambda-cloudwatch.ts
  src/provider/aws/execution/aws-lambda-codebuild.ts
  src/provider/aws/execution/aws-lambda-codepipeline.ts
  src/provider/aws/execution/aws-lambda-cognito.ts
  src/provider/aws/execution/aws-lambda-connect.ts
  src/provider/aws/execution/aws-lambda-dynamodb.ts
  src/provider/aws/execution/aws-lambda-eventbridge.ts
  src/provider/aws/execution/aws-lambda-iot.ts
  src/provider/aws/execution/aws-lambda-kinesis.ts
  src/provider/aws/execution/aws-lambda-lex.ts
  src/provider/aws/execution/aws-lambda-msk.ts
  src/provider/aws/execution/aws-lambda-s3.ts
  src/provider/aws/execution/aws-lambda-ses.ts
  src/provider/aws/execution/aws-lambda-sns.ts
  src/provider/aws/execution/aws-lambda-sqs.ts
  src/provider/aws/implementation.ts
  src/provider/aws/lambda.ts
Labels: enhancement

#9 fix: add missing result definition to cognito events
  src/provider/aws/lambda.ts
Labels: bug
